name: Auto Accept Collabs

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-create-collabs@master
        with:
          TOKEN: ${{ secrets.ACTIONS }}
